name: 'build-test'
description: 'Build and test the projects in local cadence'
inputs:
  config:
    description: 'The build configuration'
    default: Release
    required: true
  working-directory:
    description: 'The working directory'
    required: true
runs:
  using: "composite"
  steps:  
      
  # Restore dependencies
  - name: Restore
    run: dotnet restore
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    
  # Build
  - name: Build
    run: dotnet build --no-restore -c ${{ inputs.config }}
    shell: bash
    working-directory: ${{ inputs.working-directory }}
      
  # Test
  - name: Test
    run: dotnet test --no-build --verbosity normal
    shell: bash
    working-directory: ${{ inputs.working-directory }}
