name: 'build-test'
description: 'Build and test the projects in local cadence'
inputs:
  config:
    description: 'The build configuration'
    default: Release
    required: true
runs:
  using: "composite"
  steps:
  
  # Setup .Net with global.json
  - name: Setup .NET
    uses: actions/setup-dotnet@v1
      
  # Restore dependencies
  - name: Restore
    run: dotnet restore
    shell: bash
    
  # Build
  - name: Build
    run: dotnet build --no-restore -c ${{ inputs.config }}
    shell: bash
      
  # Test
  - name: Test
    run: dotnet test --no-build --verbosity normal
    shell: bash
