# CI is always local for a single repo
- name: Build metadata
  run: |
    echo "PI_CI_REFERENCE=local" >> $GITHUB_ENV
    continue-on-error: false

# Setup .Net with global.json
- name: Setup .NET
  uses: actions/setup-dotnet@v1
      
# Restore dependencies
- name: Restore
  run: dotnet restore
    
# Build
- name: Build
  run: dotnet build --no-restore
      
# Test
- name: Test
  run: dotnet test --no-build --verbosity normal
